# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute Allan Variance
#' @description Computation of allan variance
#' @usage allan_variance(x)
#' @param x A \code{vector} with dimensions N x 1. 
#' @return av A \code{matrix} that contains the cluster size as the first column and the allan variance as the second.
#' @author JJB
#' @examples
#' white.noise = rnorm(500, 0, 1)
#' allan_variance(white.noise)
allan_variance <- function(x) {
    .Call('GMWM_allan_variance', PACKAGE = 'GMWM', x)
}

